Repository octokit/plugin-enterprise-cloud.js, pull requests merged in 2023-06, with the labels that each got.

#442 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  scripts/update-endpoints/code.js
  src/endpoints-to-methods.ts
  src/generated/endpoints.ts
  src/types.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#437 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: Type: Breaking change, Type: Maintenance

#447 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
